### ISSUE TITLE
请求时发生错误 {'message': 'The number of <image> tokens does not match the number of image urls'}}

### ISSUE THREAD

**Issue by Dimensionzw** [NetEase-Media/grps_trtllm#3]
请求体内传输图像可以用类似下面的base64形式吗：
```
 messages=[{
                'role':
                    'user',
                'content': [{
                    'type': 'text',
                    'text': self.query
                }, {
                    'type': 'image_url',
                    'image_url': {
                        "url": f"data:image/jpeg;base64,{base64_img}"
                    },
                }],
            }],
```
当前使用base64传输图像报错
```
Traceback (most recent call last):
  File "/opt/nas/p/zhangwei/multi_inference/lmdeploy_http_test.py", line 166, in <module>
    main()
  File "/opt/nas/p/zhangwei/multi_inference/lmdeploy_http_test.py", line 163, in main
    model.all_dataset_time_test(result_file_path)
  File "/opt/nas/p/zhangwei/multi_inference/lmdeploy_http_test.py", line 136, in all_dataset_time_test
    infer_time = self.first_token_test(img_path, self.query)
  File "/opt/nas/p/zhangwei/multi_inference/lmdeploy_http_test.py", line 51, in first_token_test
    response = self.client.chat.completions.create(
  File "/opt/nas/p/conda/envs/multimodel_zw/lib/python3.10/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/opt/nas/p/conda/envs/multimodel_zw/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 704, in create
    return self._post(
  File "/opt/nas/p/conda/envs/multimodel_zw/lib/python3.10/site-packages/openai/_base_client.py", line 1270, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/opt/nas/p/conda/envs/multimodel_zw/lib/python3.10/site-packages/openai/_base_client.py", line 947, in request
    return self._request(
  File "/opt/nas/p/conda/envs/multimodel_zw/lib/python3.10/site-packages/openai/_base_client.py", line 1036, in _request
    return self._retry_request(
  File "/opt/nas/p/conda/envs/multimodel_zw/lib/python3.10/site-packages/openai/_base_client.py", line 1085, in _retry_request
    return self._request(
  File "/opt/nas/p/conda/envs/multimodel_zw/lib/python3.10/site-packages/openai/_base_client.py", line 1036, in _request
    return self._retry_request(
  File "/opt/nas/p/conda/envs/multimodel_zw/lib/python3.10/site-packages/openai/_base_client.py", line 1085, in _retry_request
    return self._request(
  File "/opt/nas/p/conda/envs/multimodel_zw/lib/python3.10/site-packages/openai/_base_client.py", line 1051, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: Error code: 500 - {'error': {'message': 'The number of <image> tokens does not match the number of image urls'}}
```
后续使用本地路径同样报上面的错误

**Comment by zhaocc1106** [comment]
> 请求体内传输图像可以用类似下面的base64形式吗：
> 
> ```
>  messages=[{
>                 'role':
>                     'user',
>                 'content': [{
>                     'type': 'text',
>                     'text': self.query
>                 }, {
>                     'type': 'image_url',
>                     'image_url': {
>                         "url": f"data:image/jpeg;base64,{base64_img}"
>                     },
>                 }],
>             }],
> ```
> 
> 当前使用base64传输图像报错
> 
> ```
> Traceback (most recent call last):
>   File "/opt/nas/p/zhangwei/multi_inference/lmdeploy_http_test.py", line 166, in <module>
>     main()
>   File "/opt/nas/p/zhangwei/multi_inference/lmdeploy_http_test.py", line 163, in main
>     model.all_dataset_time_test(result_file_path)
>   File "/opt/nas/p/zhangwei/multi_inference/lmdeploy_http_test.py", line 136, in all_dataset_time_test
>     infer_time = self.first_token_test(img_path, self.query)
>   File "/opt/nas/p/zhangwei/multi_inference/lmdeploy_http_test.py", line 51, in first_token_test
>     response = self.client.chat.completions.create(
>   File "/opt/nas/p/conda/envs/multimodel_zw/lib/python3.10/site-packages/openai/_utils/_utils.py", line 274, in wrapper
>     return func(*args, **kwargs)
>   File "/opt/nas/p/conda/envs/multimodel_zw/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 704, in create
>     return self._post(
>   File "/opt/nas/p/conda/envs/multimodel_zw/lib/python3.10/site-packages/openai/_base_client.py", line 1270, in post
>     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
>   File "/opt/nas/p/conda/envs/multimodel_zw/lib/python3.10/site-packages/openai/_base_client.py", line 947, in request
>     return self._request(
>   File "/opt/nas/p/conda/envs/multimodel_zw/lib/python3.10/site-packages/openai/_base_client.py", line 1036, in _request
>     return self._retry_request(
>   File "/opt/nas/p/conda/envs/multimodel_zw/lib/python3.10/site-packages/openai/_base_client.py", line 1085, in _retry_request
>     return self._request(
>   File "/opt/nas/p/conda/envs/multimodel_zw/lib/python3.10/site-packages/openai/_base_client.py", line 1036, in _request
>     return self._retry_request(
>   File "/opt/nas/p/conda/envs/multimodel_zw/lib/python3.10/site-packages/openai/_base_client.py", line 1085, in _retry_request
>     return self._request(
>   File "/opt/nas/p/conda/envs/multimodel_zw/lib/python3.10/site-packages/openai/_base_client.py", line 1051, in _request
>     raise self._make_status_error_from_response(err.response) from None
> openai.InternalServerError: Error code: 500 - {'error': {'message': 'The number of <image> tokens does not match the number of image urls'}}
> ```
> 
> 后续使用本地路径同样报上面的错误

当前还不支持base64传递图片，后面可以考虑支持。
第二个截图是prompt中<image>的个数需要和图片url个数一致，这个是internvl2的特殊prompt格式，具体请求可以参考：
https://github.com/NetEase-Media/grps_trtllm/blob/master/docs/internvl2.md#%E6%A8%A1%E6%8B%9F%E8%AF%B7%E6%B1%82

**Comment by Dimensionzw** [comment]
@zhaocc1106 使用特殊prompt处理后输出已正常，还是希望能支持base64的传输格式，能够用于线上的数据传输

**Comment by zhaocc1106** [comment]
> @zhaocc1106 使用特殊prompt处理后输出已正常，还是希望能支持base64的传输格式，能够用于线上的数据传输

ok~

**Comment by zhaocc1106** [comment]
> @zhaocc1106 使用特殊prompt处理后输出已正常，还是希望能支持base64的传输格式，能够用于线上的数据传输

https://github.com/NetEase-Media/grps_trtllm/commit/e37e11629e50a7a4100d5f6d521b6a7bf177386b
已支持，可以试试。
