### ISSUE TITLE
intervl2 VIT model

### ISSUE THREAD

**Issue by m-wei** [NetEase-Media/grps_trtllm#4]
rt， How is vision_encoder_bfp16.onnx generated

**Comment by zhaocc1106** [comment]
> rt， How is vision_encoder_bfp16.onnx generated

https://github.com/NetEase-Media/grps_trtllm/blob/master/docs%2Finternvl2.md#2b8b26b%E6%A8%A1%E5%9E%8B

build_vit_engine.py will generate vision_encoder_bfp16.onnx and vision_encoder_bfp16.trt.

<img width="822" alt="image" src="https://github.com/user-attachments/assets/9f72be24-193b-441d-943e-5975f538e8a7">

**Comment by m-wei** [comment]
@zhaocc1106 thank you,love you~
